// Code generated by entc, DO NOT EDIT.

package componentproperty

import (
	"time"
)

const (
	// Label holds the string label denoting the componentproperty type in the database.
	Label = "component_property"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldComponentID holds the string denoting the component_id field in the database.
	FieldComponentID = "component_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// EdgeComponent holds the string denoting the component edge name in mutations.
	EdgeComponent = "component"
	// Table holds the table name of the componentproperty in the database.
	Table = "component_properties"
	// ComponentTable is the table that holds the component relation/edge.
	ComponentTable = "component_properties"
	// ComponentInverseTable is the table name for the CustomComponent entity.
	// It exists in this package in order to avoid circular dependency with the "customcomponent" package.
	ComponentInverseTable = "custom_components"
	// ComponentColumn is the table column denoting the component relation/edge.
	ComponentColumn = "component_id"
)

// Columns holds all SQL columns for componentproperty fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldComponentID,
	FieldName,
	FieldValue,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uint64
)
