// Code generated by entc, DO NOT EDIT.

package ent

import (
	"app-api/ent/bktemplatesection"
	"app-api/ent/predicate"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BkTemplateSectionDelete is the builder for deleting a BkTemplateSection entity.
type BkTemplateSectionDelete struct {
	config
	hooks    []Hook
	mutation *BkTemplateSectionMutation
}

// Where appends a list predicates to the BkTemplateSectionDelete builder.
func (btsd *BkTemplateSectionDelete) Where(ps ...predicate.BkTemplateSection) *BkTemplateSectionDelete {
	btsd.mutation.Where(ps...)
	return btsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (btsd *BkTemplateSectionDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(btsd.hooks) == 0 {
		affected, err = btsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BkTemplateSectionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			btsd.mutation = mutation
			affected, err = btsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(btsd.hooks) - 1; i >= 0; i-- {
			if btsd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = btsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, btsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (btsd *BkTemplateSectionDelete) ExecX(ctx context.Context) int {
	n, err := btsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (btsd *BkTemplateSectionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: bktemplatesection.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: bktemplatesection.FieldID,
			},
		},
	}
	if ps := btsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, btsd.driver, _spec)
}

// BkTemplateSectionDeleteOne is the builder for deleting a single BkTemplateSection entity.
type BkTemplateSectionDeleteOne struct {
	btsd *BkTemplateSectionDelete
}

// Exec executes the deletion query.
func (btsdo *BkTemplateSectionDeleteOne) Exec(ctx context.Context) error {
	n, err := btsdo.btsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bktemplatesection.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (btsdo *BkTemplateSectionDeleteOne) ExecX(ctx context.Context) {
	btsdo.btsd.ExecX(ctx)
}
