// Code generated by entc, DO NOT EDIT.

package ent

import (
	"app-api/ent/componentproperty"
	"app-api/ent/customcomponent"
	"app-api/ent/predicate"
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CustomComponentQuery is the builder for querying CustomComponent entities.
type CustomComponentQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.CustomComponent
	// eager-loading edges.
	withProps *ComponentPropertyQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CustomComponentQuery builder.
func (ccq *CustomComponentQuery) Where(ps ...predicate.CustomComponent) *CustomComponentQuery {
	ccq.predicates = append(ccq.predicates, ps...)
	return ccq
}

// Limit adds a limit step to the query.
func (ccq *CustomComponentQuery) Limit(limit int) *CustomComponentQuery {
	ccq.limit = &limit
	return ccq
}

// Offset adds an offset step to the query.
func (ccq *CustomComponentQuery) Offset(offset int) *CustomComponentQuery {
	ccq.offset = &offset
	return ccq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ccq *CustomComponentQuery) Unique(unique bool) *CustomComponentQuery {
	ccq.unique = &unique
	return ccq
}

// Order adds an order step to the query.
func (ccq *CustomComponentQuery) Order(o ...OrderFunc) *CustomComponentQuery {
	ccq.order = append(ccq.order, o...)
	return ccq
}

// QueryProps chains the current query on the "props" edge.
func (ccq *CustomComponentQuery) QueryProps() *ComponentPropertyQuery {
	query := &ComponentPropertyQuery{config: ccq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ccq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ccq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(customcomponent.Table, customcomponent.FieldID, selector),
			sqlgraph.To(componentproperty.Table, componentproperty.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, customcomponent.PropsTable, customcomponent.PropsColumn),
		)
		fromU = sqlgraph.SetNeighbors(ccq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CustomComponent entity from the query.
// Returns a *NotFoundError when no CustomComponent was found.
func (ccq *CustomComponentQuery) First(ctx context.Context) (*CustomComponent, error) {
	nodes, err := ccq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{customcomponent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ccq *CustomComponentQuery) FirstX(ctx context.Context) *CustomComponent {
	node, err := ccq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CustomComponent ID from the query.
// Returns a *NotFoundError when no CustomComponent ID was found.
func (ccq *CustomComponentQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = ccq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{customcomponent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ccq *CustomComponentQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := ccq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CustomComponent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one CustomComponent entity is not found.
// Returns a *NotFoundError when no CustomComponent entities are found.
func (ccq *CustomComponentQuery) Only(ctx context.Context) (*CustomComponent, error) {
	nodes, err := ccq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{customcomponent.Label}
	default:
		return nil, &NotSingularError{customcomponent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ccq *CustomComponentQuery) OnlyX(ctx context.Context) *CustomComponent {
	node, err := ccq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CustomComponent ID in the query.
// Returns a *NotSingularError when exactly one CustomComponent ID is not found.
// Returns a *NotFoundError when no entities are found.
func (ccq *CustomComponentQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = ccq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{customcomponent.Label}
	default:
		err = &NotSingularError{customcomponent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ccq *CustomComponentQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := ccq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CustomComponents.
func (ccq *CustomComponentQuery) All(ctx context.Context) ([]*CustomComponent, error) {
	if err := ccq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ccq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ccq *CustomComponentQuery) AllX(ctx context.Context) []*CustomComponent {
	nodes, err := ccq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CustomComponent IDs.
func (ccq *CustomComponentQuery) IDs(ctx context.Context) ([]uint64, error) {
	var ids []uint64
	if err := ccq.Select(customcomponent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ccq *CustomComponentQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := ccq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ccq *CustomComponentQuery) Count(ctx context.Context) (int, error) {
	if err := ccq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ccq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ccq *CustomComponentQuery) CountX(ctx context.Context) int {
	count, err := ccq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ccq *CustomComponentQuery) Exist(ctx context.Context) (bool, error) {
	if err := ccq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ccq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ccq *CustomComponentQuery) ExistX(ctx context.Context) bool {
	exist, err := ccq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CustomComponentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ccq *CustomComponentQuery) Clone() *CustomComponentQuery {
	if ccq == nil {
		return nil
	}
	return &CustomComponentQuery{
		config:     ccq.config,
		limit:      ccq.limit,
		offset:     ccq.offset,
		order:      append([]OrderFunc{}, ccq.order...),
		predicates: append([]predicate.CustomComponent{}, ccq.predicates...),
		withProps:  ccq.withProps.Clone(),
		// clone intermediate query.
		sql:  ccq.sql.Clone(),
		path: ccq.path,
	}
}

// WithProps tells the query-builder to eager-load the nodes that are connected to
// the "props" edge. The optional arguments are used to configure the query builder of the edge.
func (ccq *CustomComponentQuery) WithProps(opts ...func(*ComponentPropertyQuery)) *CustomComponentQuery {
	query := &ComponentPropertyQuery{config: ccq.config}
	for _, opt := range opts {
		opt(query)
	}
	ccq.withProps = query
	return ccq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CustomComponent.Query().
//		GroupBy(customcomponent.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ccq *CustomComponentQuery) GroupBy(field string, fields ...string) *CustomComponentGroupBy {
	group := &CustomComponentGroupBy{config: ccq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ccq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ccq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt"`
//	}
//
//	client.CustomComponent.Query().
//		Select(customcomponent.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (ccq *CustomComponentQuery) Select(fields ...string) *CustomComponentSelect {
	ccq.fields = append(ccq.fields, fields...)
	return &CustomComponentSelect{CustomComponentQuery: ccq}
}

func (ccq *CustomComponentQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ccq.fields {
		if !customcomponent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ccq.path != nil {
		prev, err := ccq.path(ctx)
		if err != nil {
			return err
		}
		ccq.sql = prev
	}
	return nil
}

func (ccq *CustomComponentQuery) sqlAll(ctx context.Context) ([]*CustomComponent, error) {
	var (
		nodes       = []*CustomComponent{}
		_spec       = ccq.querySpec()
		loadedTypes = [1]bool{
			ccq.withProps != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &CustomComponent{config: ccq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ccq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := ccq.withProps; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[uint64]*CustomComponent)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Props = []*ComponentProperty{}
		}
		query.Where(predicate.ComponentProperty(func(s *sql.Selector) {
			s.Where(sql.InValues(customcomponent.PropsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.ComponentID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "component_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.Props = append(node.Edges.Props, n)
		}
	}

	return nodes, nil
}

func (ccq *CustomComponentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ccq.querySpec()
	return sqlgraph.CountNodes(ctx, ccq.driver, _spec)
}

func (ccq *CustomComponentQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ccq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ccq *CustomComponentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   customcomponent.Table,
			Columns: customcomponent.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: customcomponent.FieldID,
			},
		},
		From:   ccq.sql,
		Unique: true,
	}
	if unique := ccq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ccq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, customcomponent.FieldID)
		for i := range fields {
			if fields[i] != customcomponent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ccq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ccq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ccq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ccq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ccq *CustomComponentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ccq.driver.Dialect())
	t1 := builder.Table(customcomponent.Table)
	columns := ccq.fields
	if len(columns) == 0 {
		columns = customcomponent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ccq.sql != nil {
		selector = ccq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range ccq.predicates {
		p(selector)
	}
	for _, p := range ccq.order {
		p(selector)
	}
	if offset := ccq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ccq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CustomComponentGroupBy is the group-by builder for CustomComponent entities.
type CustomComponentGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ccgb *CustomComponentGroupBy) Aggregate(fns ...AggregateFunc) *CustomComponentGroupBy {
	ccgb.fns = append(ccgb.fns, fns...)
	return ccgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ccgb *CustomComponentGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ccgb.path(ctx)
	if err != nil {
		return err
	}
	ccgb.sql = query
	return ccgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ccgb *CustomComponentGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ccgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (ccgb *CustomComponentGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ccgb.fields) > 1 {
		return nil, errors.New("ent: CustomComponentGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ccgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ccgb *CustomComponentGroupBy) StringsX(ctx context.Context) []string {
	v, err := ccgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ccgb *CustomComponentGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ccgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{customcomponent.Label}
	default:
		err = fmt.Errorf("ent: CustomComponentGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ccgb *CustomComponentGroupBy) StringX(ctx context.Context) string {
	v, err := ccgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (ccgb *CustomComponentGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ccgb.fields) > 1 {
		return nil, errors.New("ent: CustomComponentGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ccgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ccgb *CustomComponentGroupBy) IntsX(ctx context.Context) []int {
	v, err := ccgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ccgb *CustomComponentGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ccgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{customcomponent.Label}
	default:
		err = fmt.Errorf("ent: CustomComponentGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ccgb *CustomComponentGroupBy) IntX(ctx context.Context) int {
	v, err := ccgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ccgb *CustomComponentGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ccgb.fields) > 1 {
		return nil, errors.New("ent: CustomComponentGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ccgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ccgb *CustomComponentGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ccgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ccgb *CustomComponentGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ccgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{customcomponent.Label}
	default:
		err = fmt.Errorf("ent: CustomComponentGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ccgb *CustomComponentGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ccgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (ccgb *CustomComponentGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ccgb.fields) > 1 {
		return nil, errors.New("ent: CustomComponentGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ccgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ccgb *CustomComponentGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ccgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ccgb *CustomComponentGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ccgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{customcomponent.Label}
	default:
		err = fmt.Errorf("ent: CustomComponentGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ccgb *CustomComponentGroupBy) BoolX(ctx context.Context) bool {
	v, err := ccgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ccgb *CustomComponentGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ccgb.fields {
		if !customcomponent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ccgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ccgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ccgb *CustomComponentGroupBy) sqlQuery() *sql.Selector {
	selector := ccgb.sql.Select()
	aggregation := make([]string, 0, len(ccgb.fns))
	for _, fn := range ccgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ccgb.fields)+len(ccgb.fns))
		for _, f := range ccgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ccgb.fields...)...)
}

// CustomComponentSelect is the builder for selecting fields of CustomComponent entities.
type CustomComponentSelect struct {
	*CustomComponentQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ccs *CustomComponentSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ccs.prepareQuery(ctx); err != nil {
		return err
	}
	ccs.sql = ccs.CustomComponentQuery.sqlQuery(ctx)
	return ccs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ccs *CustomComponentSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ccs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ccs *CustomComponentSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ccs.fields) > 1 {
		return nil, errors.New("ent: CustomComponentSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ccs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ccs *CustomComponentSelect) StringsX(ctx context.Context) []string {
	v, err := ccs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ccs *CustomComponentSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ccs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{customcomponent.Label}
	default:
		err = fmt.Errorf("ent: CustomComponentSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ccs *CustomComponentSelect) StringX(ctx context.Context) string {
	v, err := ccs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ccs *CustomComponentSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ccs.fields) > 1 {
		return nil, errors.New("ent: CustomComponentSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ccs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ccs *CustomComponentSelect) IntsX(ctx context.Context) []int {
	v, err := ccs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ccs *CustomComponentSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ccs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{customcomponent.Label}
	default:
		err = fmt.Errorf("ent: CustomComponentSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ccs *CustomComponentSelect) IntX(ctx context.Context) int {
	v, err := ccs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ccs *CustomComponentSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ccs.fields) > 1 {
		return nil, errors.New("ent: CustomComponentSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ccs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ccs *CustomComponentSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ccs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ccs *CustomComponentSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ccs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{customcomponent.Label}
	default:
		err = fmt.Errorf("ent: CustomComponentSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ccs *CustomComponentSelect) Float64X(ctx context.Context) float64 {
	v, err := ccs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ccs *CustomComponentSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ccs.fields) > 1 {
		return nil, errors.New("ent: CustomComponentSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ccs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ccs *CustomComponentSelect) BoolsX(ctx context.Context) []bool {
	v, err := ccs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ccs *CustomComponentSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ccs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{customcomponent.Label}
	default:
		err = fmt.Errorf("ent: CustomComponentSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ccs *CustomComponentSelect) BoolX(ctx context.Context) bool {
	v, err := ccs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ccs *CustomComponentSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ccs.sql.Query()
	if err := ccs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
