// Code generated by entc, DO NOT EDIT.

package ent

import (
	"app-api/ent/globaltemplate"
	"app-api/ent/predicate"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GlobalTemplateDelete is the builder for deleting a GlobalTemplate entity.
type GlobalTemplateDelete struct {
	config
	hooks    []Hook
	mutation *GlobalTemplateMutation
}

// Where appends a list predicates to the GlobalTemplateDelete builder.
func (gtd *GlobalTemplateDelete) Where(ps ...predicate.GlobalTemplate) *GlobalTemplateDelete {
	gtd.mutation.Where(ps...)
	return gtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gtd *GlobalTemplateDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(gtd.hooks) == 0 {
		affected, err = gtd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GlobalTemplateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gtd.mutation = mutation
			affected, err = gtd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(gtd.hooks) - 1; i >= 0; i-- {
			if gtd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gtd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gtd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (gtd *GlobalTemplateDelete) ExecX(ctx context.Context) int {
	n, err := gtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gtd *GlobalTemplateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: globaltemplate.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: globaltemplate.FieldID,
			},
		},
	}
	if ps := gtd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, gtd.driver, _spec)
}

// GlobalTemplateDeleteOne is the builder for deleting a single GlobalTemplate entity.
type GlobalTemplateDeleteOne struct {
	gtd *GlobalTemplateDelete
}

// Exec executes the deletion query.
func (gtdo *GlobalTemplateDeleteOne) Exec(ctx context.Context) error {
	n, err := gtdo.gtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{globaltemplate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gtdo *GlobalTemplateDeleteOne) ExecX(ctx context.Context) {
	gtdo.gtd.ExecX(ctx)
}
