// Code generated by entc, DO NOT EDIT.

package ent

import (
	"app-api/ent/globaltemplate"
	"app-api/ent/predicate"
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GlobalTemplateQuery is the builder for querying GlobalTemplate entities.
type GlobalTemplateQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.GlobalTemplate
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GlobalTemplateQuery builder.
func (gtq *GlobalTemplateQuery) Where(ps ...predicate.GlobalTemplate) *GlobalTemplateQuery {
	gtq.predicates = append(gtq.predicates, ps...)
	return gtq
}

// Limit adds a limit step to the query.
func (gtq *GlobalTemplateQuery) Limit(limit int) *GlobalTemplateQuery {
	gtq.limit = &limit
	return gtq
}

// Offset adds an offset step to the query.
func (gtq *GlobalTemplateQuery) Offset(offset int) *GlobalTemplateQuery {
	gtq.offset = &offset
	return gtq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gtq *GlobalTemplateQuery) Unique(unique bool) *GlobalTemplateQuery {
	gtq.unique = &unique
	return gtq
}

// Order adds an order step to the query.
func (gtq *GlobalTemplateQuery) Order(o ...OrderFunc) *GlobalTemplateQuery {
	gtq.order = append(gtq.order, o...)
	return gtq
}

// First returns the first GlobalTemplate entity from the query.
// Returns a *NotFoundError when no GlobalTemplate was found.
func (gtq *GlobalTemplateQuery) First(ctx context.Context) (*GlobalTemplate, error) {
	nodes, err := gtq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{globaltemplate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gtq *GlobalTemplateQuery) FirstX(ctx context.Context) *GlobalTemplate {
	node, err := gtq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GlobalTemplate ID from the query.
// Returns a *NotFoundError when no GlobalTemplate ID was found.
func (gtq *GlobalTemplateQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = gtq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{globaltemplate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gtq *GlobalTemplateQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := gtq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GlobalTemplate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one GlobalTemplate entity is not found.
// Returns a *NotFoundError when no GlobalTemplate entities are found.
func (gtq *GlobalTemplateQuery) Only(ctx context.Context) (*GlobalTemplate, error) {
	nodes, err := gtq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{globaltemplate.Label}
	default:
		return nil, &NotSingularError{globaltemplate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gtq *GlobalTemplateQuery) OnlyX(ctx context.Context) *GlobalTemplate {
	node, err := gtq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GlobalTemplate ID in the query.
// Returns a *NotSingularError when exactly one GlobalTemplate ID is not found.
// Returns a *NotFoundError when no entities are found.
func (gtq *GlobalTemplateQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = gtq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{globaltemplate.Label}
	default:
		err = &NotSingularError{globaltemplate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gtq *GlobalTemplateQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := gtq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GlobalTemplates.
func (gtq *GlobalTemplateQuery) All(ctx context.Context) ([]*GlobalTemplate, error) {
	if err := gtq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return gtq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (gtq *GlobalTemplateQuery) AllX(ctx context.Context) []*GlobalTemplate {
	nodes, err := gtq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GlobalTemplate IDs.
func (gtq *GlobalTemplateQuery) IDs(ctx context.Context) ([]uint64, error) {
	var ids []uint64
	if err := gtq.Select(globaltemplate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gtq *GlobalTemplateQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := gtq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gtq *GlobalTemplateQuery) Count(ctx context.Context) (int, error) {
	if err := gtq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return gtq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (gtq *GlobalTemplateQuery) CountX(ctx context.Context) int {
	count, err := gtq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gtq *GlobalTemplateQuery) Exist(ctx context.Context) (bool, error) {
	if err := gtq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return gtq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (gtq *GlobalTemplateQuery) ExistX(ctx context.Context) bool {
	exist, err := gtq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GlobalTemplateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gtq *GlobalTemplateQuery) Clone() *GlobalTemplateQuery {
	if gtq == nil {
		return nil
	}
	return &GlobalTemplateQuery{
		config:     gtq.config,
		limit:      gtq.limit,
		offset:     gtq.offset,
		order:      append([]OrderFunc{}, gtq.order...),
		predicates: append([]predicate.GlobalTemplate{}, gtq.predicates...),
		// clone intermediate query.
		sql:  gtq.sql.Clone(),
		path: gtq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GlobalTemplate.Query().
//		GroupBy(globaltemplate.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (gtq *GlobalTemplateQuery) GroupBy(field string, fields ...string) *GlobalTemplateGroupBy {
	group := &GlobalTemplateGroupBy{config: gtq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := gtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return gtq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt"`
//	}
//
//	client.GlobalTemplate.Query().
//		Select(globaltemplate.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (gtq *GlobalTemplateQuery) Select(fields ...string) *GlobalTemplateSelect {
	gtq.fields = append(gtq.fields, fields...)
	return &GlobalTemplateSelect{GlobalTemplateQuery: gtq}
}

func (gtq *GlobalTemplateQuery) prepareQuery(ctx context.Context) error {
	for _, f := range gtq.fields {
		if !globaltemplate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gtq.path != nil {
		prev, err := gtq.path(ctx)
		if err != nil {
			return err
		}
		gtq.sql = prev
	}
	return nil
}

func (gtq *GlobalTemplateQuery) sqlAll(ctx context.Context) ([]*GlobalTemplate, error) {
	var (
		nodes = []*GlobalTemplate{}
		_spec = gtq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &GlobalTemplate{config: gtq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, gtq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (gtq *GlobalTemplateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gtq.querySpec()
	return sqlgraph.CountNodes(ctx, gtq.driver, _spec)
}

func (gtq *GlobalTemplateQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := gtq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (gtq *GlobalTemplateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   globaltemplate.Table,
			Columns: globaltemplate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: globaltemplate.FieldID,
			},
		},
		From:   gtq.sql,
		Unique: true,
	}
	if unique := gtq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := gtq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, globaltemplate.FieldID)
		for i := range fields {
			if fields[i] != globaltemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gtq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gtq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gtq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gtq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gtq *GlobalTemplateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gtq.driver.Dialect())
	t1 := builder.Table(globaltemplate.Table)
	columns := gtq.fields
	if len(columns) == 0 {
		columns = globaltemplate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gtq.sql != nil {
		selector = gtq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range gtq.predicates {
		p(selector)
	}
	for _, p := range gtq.order {
		p(selector)
	}
	if offset := gtq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gtq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GlobalTemplateGroupBy is the group-by builder for GlobalTemplate entities.
type GlobalTemplateGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gtgb *GlobalTemplateGroupBy) Aggregate(fns ...AggregateFunc) *GlobalTemplateGroupBy {
	gtgb.fns = append(gtgb.fns, fns...)
	return gtgb
}

// Scan applies the group-by query and scans the result into the given value.
func (gtgb *GlobalTemplateGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := gtgb.path(ctx)
	if err != nil {
		return err
	}
	gtgb.sql = query
	return gtgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (gtgb *GlobalTemplateGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := gtgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (gtgb *GlobalTemplateGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(gtgb.fields) > 1 {
		return nil, errors.New("ent: GlobalTemplateGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := gtgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (gtgb *GlobalTemplateGroupBy) StringsX(ctx context.Context) []string {
	v, err := gtgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gtgb *GlobalTemplateGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = gtgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{globaltemplate.Label}
	default:
		err = fmt.Errorf("ent: GlobalTemplateGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (gtgb *GlobalTemplateGroupBy) StringX(ctx context.Context) string {
	v, err := gtgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (gtgb *GlobalTemplateGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(gtgb.fields) > 1 {
		return nil, errors.New("ent: GlobalTemplateGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := gtgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (gtgb *GlobalTemplateGroupBy) IntsX(ctx context.Context) []int {
	v, err := gtgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gtgb *GlobalTemplateGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = gtgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{globaltemplate.Label}
	default:
		err = fmt.Errorf("ent: GlobalTemplateGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (gtgb *GlobalTemplateGroupBy) IntX(ctx context.Context) int {
	v, err := gtgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (gtgb *GlobalTemplateGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(gtgb.fields) > 1 {
		return nil, errors.New("ent: GlobalTemplateGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := gtgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (gtgb *GlobalTemplateGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := gtgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gtgb *GlobalTemplateGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = gtgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{globaltemplate.Label}
	default:
		err = fmt.Errorf("ent: GlobalTemplateGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (gtgb *GlobalTemplateGroupBy) Float64X(ctx context.Context) float64 {
	v, err := gtgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (gtgb *GlobalTemplateGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(gtgb.fields) > 1 {
		return nil, errors.New("ent: GlobalTemplateGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := gtgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (gtgb *GlobalTemplateGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := gtgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gtgb *GlobalTemplateGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = gtgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{globaltemplate.Label}
	default:
		err = fmt.Errorf("ent: GlobalTemplateGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (gtgb *GlobalTemplateGroupBy) BoolX(ctx context.Context) bool {
	v, err := gtgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (gtgb *GlobalTemplateGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range gtgb.fields {
		if !globaltemplate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := gtgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gtgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (gtgb *GlobalTemplateGroupBy) sqlQuery() *sql.Selector {
	selector := gtgb.sql.Select()
	aggregation := make([]string, 0, len(gtgb.fns))
	for _, fn := range gtgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(gtgb.fields)+len(gtgb.fns))
		for _, f := range gtgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(gtgb.fields...)...)
}

// GlobalTemplateSelect is the builder for selecting fields of GlobalTemplate entities.
type GlobalTemplateSelect struct {
	*GlobalTemplateQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (gts *GlobalTemplateSelect) Scan(ctx context.Context, v interface{}) error {
	if err := gts.prepareQuery(ctx); err != nil {
		return err
	}
	gts.sql = gts.GlobalTemplateQuery.sqlQuery(ctx)
	return gts.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (gts *GlobalTemplateSelect) ScanX(ctx context.Context, v interface{}) {
	if err := gts.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (gts *GlobalTemplateSelect) Strings(ctx context.Context) ([]string, error) {
	if len(gts.fields) > 1 {
		return nil, errors.New("ent: GlobalTemplateSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := gts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (gts *GlobalTemplateSelect) StringsX(ctx context.Context) []string {
	v, err := gts.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (gts *GlobalTemplateSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = gts.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{globaltemplate.Label}
	default:
		err = fmt.Errorf("ent: GlobalTemplateSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (gts *GlobalTemplateSelect) StringX(ctx context.Context) string {
	v, err := gts.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (gts *GlobalTemplateSelect) Ints(ctx context.Context) ([]int, error) {
	if len(gts.fields) > 1 {
		return nil, errors.New("ent: GlobalTemplateSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := gts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (gts *GlobalTemplateSelect) IntsX(ctx context.Context) []int {
	v, err := gts.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (gts *GlobalTemplateSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = gts.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{globaltemplate.Label}
	default:
		err = fmt.Errorf("ent: GlobalTemplateSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (gts *GlobalTemplateSelect) IntX(ctx context.Context) int {
	v, err := gts.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (gts *GlobalTemplateSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(gts.fields) > 1 {
		return nil, errors.New("ent: GlobalTemplateSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := gts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (gts *GlobalTemplateSelect) Float64sX(ctx context.Context) []float64 {
	v, err := gts.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (gts *GlobalTemplateSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = gts.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{globaltemplate.Label}
	default:
		err = fmt.Errorf("ent: GlobalTemplateSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (gts *GlobalTemplateSelect) Float64X(ctx context.Context) float64 {
	v, err := gts.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (gts *GlobalTemplateSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(gts.fields) > 1 {
		return nil, errors.New("ent: GlobalTemplateSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := gts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (gts *GlobalTemplateSelect) BoolsX(ctx context.Context) []bool {
	v, err := gts.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (gts *GlobalTemplateSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = gts.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{globaltemplate.Label}
	default:
		err = fmt.Errorf("ent: GlobalTemplateSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (gts *GlobalTemplateSelect) BoolX(ctx context.Context) bool {
	v, err := gts.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (gts *GlobalTemplateSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := gts.sql.Query()
	if err := gts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
