// Code generated by entc, DO NOT EDIT.

package ent

// IsEntify for supporting federated gqlgen.
func (q BkTemplateSection) IsEntity() {}

// IsEntify for supporting federated gqlgen.
func (q ComponentProperty) IsEntity() {}

// IsEntify for supporting federated gqlgen.
func (q CustomComponent) IsEntity() {}

// IsEntify for supporting federated gqlgen.
func (q GlobalTemplate) IsEntity() {}

// IsEntify for supporting federated gqlgen.
func (q Shop) IsEntity() {}

// IsEntify for supporting federated gqlgen.
func (q TemplateSection) IsEntity() {}

// IsEntify for supporting federated gqlgen.
func (q TemplateSectionVersion) IsEntity() {}

// IsEntify for supporting federated gqlgen.
func (q Theme) IsEntity() {}

// IsEntify for supporting federated gqlgen.
func (q ThemeTemplate) IsEntity() {}

// IsEntify for supporting federated gqlgen.
func (q Todo) IsEntity() {}
