// Code generated by entc, DO NOT EDIT.

package ent

import (
	"app-api/ent/shop"
	"app-api/ent/theme"
	"app-api/ent/themetemplate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShopCreate is the builder for creating a Shop entity.
type ShopCreate struct {
	config
	mutation *ShopMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (sc *ShopCreate) SetCreatedAt(t time.Time) *ShopCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *ShopCreate) SetNillableCreatedAt(t *time.Time) *ShopCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetUpdatedAt sets the "updated_at" field.
func (sc *ShopCreate) SetUpdatedAt(t time.Time) *ShopCreate {
	sc.mutation.SetUpdatedAt(t)
	return sc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sc *ShopCreate) SetNillableUpdatedAt(t *time.Time) *ShopCreate {
	if t != nil {
		sc.SetUpdatedAt(*t)
	}
	return sc
}

// SetDeletedAt sets the "deleted_at" field.
func (sc *ShopCreate) SetDeletedAt(t time.Time) *ShopCreate {
	sc.mutation.SetDeletedAt(t)
	return sc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sc *ShopCreate) SetNillableDeletedAt(t *time.Time) *ShopCreate {
	if t != nil {
		sc.SetDeletedAt(*t)
	}
	return sc
}

// SetShopName sets the "shop_name" field.
func (sc *ShopCreate) SetShopName(s string) *ShopCreate {
	sc.mutation.SetShopName(s)
	return sc
}

// SetNillableShopName sets the "shop_name" field if the given value is not nil.
func (sc *ShopCreate) SetNillableShopName(s *string) *ShopCreate {
	if s != nil {
		sc.SetShopName(*s)
	}
	return sc
}

// SetDefaultDomain sets the "default_domain" field.
func (sc *ShopCreate) SetDefaultDomain(s string) *ShopCreate {
	sc.mutation.SetDefaultDomain(s)
	return sc
}

// SetCustomDomain sets the "custom_domain" field.
func (sc *ShopCreate) SetCustomDomain(s string) *ShopCreate {
	sc.mutation.SetCustomDomain(s)
	return sc
}

// SetID sets the "id" field.
func (sc *ShopCreate) SetID(u uint64) *ShopCreate {
	sc.mutation.SetID(u)
	return sc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (sc *ShopCreate) SetNillableID(u *uint64) *ShopCreate {
	if u != nil {
		sc.SetID(*u)
	}
	return sc
}

// AddThemeIDs adds the "themes" edge to the Theme entity by IDs.
func (sc *ShopCreate) AddThemeIDs(ids ...uint64) *ShopCreate {
	sc.mutation.AddThemeIDs(ids...)
	return sc
}

// AddThemes adds the "themes" edges to the Theme entity.
func (sc *ShopCreate) AddThemes(t ...*Theme) *ShopCreate {
	ids := make([]uint64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return sc.AddThemeIDs(ids...)
}

// AddThemeTemplateIDs adds the "themeTemplates" edge to the ThemeTemplate entity by IDs.
func (sc *ShopCreate) AddThemeTemplateIDs(ids ...uint64) *ShopCreate {
	sc.mutation.AddThemeTemplateIDs(ids...)
	return sc
}

// AddThemeTemplates adds the "themeTemplates" edges to the ThemeTemplate entity.
func (sc *ShopCreate) AddThemeTemplates(t ...*ThemeTemplate) *ShopCreate {
	ids := make([]uint64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return sc.AddThemeTemplateIDs(ids...)
}

// Mutation returns the ShopMutation object of the builder.
func (sc *ShopCreate) Mutation() *ShopMutation {
	return sc.mutation
}

// Save creates the Shop in the database.
func (sc *ShopCreate) Save(ctx context.Context) (*Shop, error) {
	var (
		err  error
		node *Shop
	)
	sc.defaults()
	if len(sc.hooks) == 0 {
		if err = sc.check(); err != nil {
			return nil, err
		}
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ShopMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sc.check(); err != nil {
				return nil, err
			}
			sc.mutation = mutation
			if node, err = sc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			if sc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *ShopCreate) SaveX(ctx context.Context) *Shop {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *ShopCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *ShopCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *ShopCreate) defaults() {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := shop.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		v := shop.DefaultUpdatedAt()
		sc.mutation.SetUpdatedAt(v)
	}
	if _, ok := sc.mutation.ShopName(); !ok {
		v := shop.DefaultShopName
		sc.mutation.SetShopName(v)
	}
	if _, ok := sc.mutation.ID(); !ok {
		v := shop.DefaultID()
		sc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *ShopCreate) check() error {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "created_at"`)}
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "updated_at"`)}
	}
	if _, ok := sc.mutation.ShopName(); !ok {
		return &ValidationError{Name: "shop_name", err: errors.New(`ent: missing required field "shop_name"`)}
	}
	if v, ok := sc.mutation.ShopName(); ok {
		if err := shop.ShopNameValidator(v); err != nil {
			return &ValidationError{Name: "shop_name", err: fmt.Errorf(`ent: validator failed for field "shop_name": %w`, err)}
		}
	}
	if _, ok := sc.mutation.DefaultDomain(); !ok {
		return &ValidationError{Name: "default_domain", err: errors.New(`ent: missing required field "default_domain"`)}
	}
	if v, ok := sc.mutation.DefaultDomain(); ok {
		if err := shop.DefaultDomainValidator(v); err != nil {
			return &ValidationError{Name: "default_domain", err: fmt.Errorf(`ent: validator failed for field "default_domain": %w`, err)}
		}
	}
	if _, ok := sc.mutation.CustomDomain(); !ok {
		return &ValidationError{Name: "custom_domain", err: errors.New(`ent: missing required field "custom_domain"`)}
	}
	if v, ok := sc.mutation.CustomDomain(); ok {
		if err := shop.CustomDomainValidator(v); err != nil {
			return &ValidationError{Name: "custom_domain", err: fmt.Errorf(`ent: validator failed for field "custom_domain": %w`, err)}
		}
	}
	return nil
}

func (sc *ShopCreate) sqlSave(ctx context.Context) (*Shop, error) {
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	return _node, nil
}

func (sc *ShopCreate) createSpec() (*Shop, *sqlgraph.CreateSpec) {
	var (
		_node = &Shop{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: shop.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: shop.FieldID,
			},
		}
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: shop.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: shop.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := sc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: shop.FieldDeletedAt,
		})
		_node.DeletedAt = &value
	}
	if value, ok := sc.mutation.ShopName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: shop.FieldShopName,
		})
		_node.ShopName = value
	}
	if value, ok := sc.mutation.DefaultDomain(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: shop.FieldDefaultDomain,
		})
		_node.DefaultDomain = value
	}
	if value, ok := sc.mutation.CustomDomain(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: shop.FieldCustomDomain,
		})
		_node.CustomDomain = value
	}
	if nodes := sc.mutation.ThemesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shop.ThemesTable,
			Columns: []string{shop.ThemesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: theme.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.ThemeTemplatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shop.ThemeTemplatesTable,
			Columns: []string{shop.ThemeTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: themetemplate.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ShopCreateBulk is the builder for creating many Shop entities in bulk.
type ShopCreateBulk struct {
	config
	builders []*ShopCreate
}

// Save creates the Shop entities in the database.
func (scb *ShopCreateBulk) Save(ctx context.Context) ([]*Shop, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Shop, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShopMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *ShopCreateBulk) SaveX(ctx context.Context) []*Shop {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *ShopCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *ShopCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
