// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BkTemplateSection is the predicate function for bktemplatesection builders.
type BkTemplateSection func(*sql.Selector)

// ComponentProperty is the predicate function for componentproperty builders.
type ComponentProperty func(*sql.Selector)

// CustomComponent is the predicate function for customcomponent builders.
type CustomComponent func(*sql.Selector)

// GlobalTemplate is the predicate function for globaltemplate builders.
type GlobalTemplate func(*sql.Selector)

// Shop is the predicate function for shop builders.
type Shop func(*sql.Selector)

// TemplateSection is the predicate function for templatesection builders.
type TemplateSection func(*sql.Selector)

// TemplateSectionVersion is the predicate function for templatesectionversion builders.
type TemplateSectionVersion func(*sql.Selector)

// Theme is the predicate function for theme builders.
type Theme func(*sql.Selector)

// ThemeTemplate is the predicate function for themetemplate builders.
type ThemeTemplate func(*sql.Selector)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)
